### ISSUE TITLE
Docs - How to implement JWT authentication to a React Template

### ISSUE THREAD

**Issue by app-generator** [app-generator/react-soft-ui-dashboard#7]
Hello @StefanENC,

The implementation process should be documented in full on a separate repository [docs mirror](https://github.com/app-generator/docs-mirror). Once the content quality is good, we will merge the content in Gitbook. 

Here is the invitation: 
https://github.com/app-generator/docs-mirror/invitations

Please provide all steps that a beginner should follow in order to code this feature to another React Template. I will drop below a few sections (feel free to add more). Keep in mind that the content targets beginners: 

- Analyze Codebase
- Detect master pages
- Add dependencies 
  - `axios`
  - formic
- Code app store 
- Code Guard component that detects the authentication state
- Update routes 
- Implement Sign IN via `axios`
- Implement Logout 

The page that should be updated is this one:
https://github.com/app-generator/docs-mirror/blob/main/react-implement-jwt-authentication.md

Ty!

**Comment by StefanENC** [comment]
Can this be closed? - @app-generator
